branch-defaults:
  create-preview:
    environment: hice-frontend-pr18
environment-defaults:
  hice-frontend-pr18:
    branch: null
    repository: null
global:
  application_name: hice_frontend
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
