name: Generate PR Description

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pr-description:
    if: ${{ github.event.label.name == 'pr-description' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/cli/cli/releases/download/v2.14.3/gh_2.14.3_linux_amd64.tar.gz -o ghcli.tar.gz
          tar -xzf ghcli.tar.gz
          sudo mv gh_2.14.3_linux_amd64/bin/gh /usr/local/bin/
          gh --version

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > gh_token.txt
          gh auth login --with-token < gh_token.txt
          rm gh_token.txt

      - name: Get PR Diff
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_description.py $OPENAI_API_KEY

      - name: Update PR Title and Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('description.txt', 'utf8');
            const title = fs.readFileSync('title.txt', 'utf8');
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: title,
              body: description
            });
