name: Prettier Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Prettier check
        run: npm run prettier:check
