name: Remove Preview Environment on Merge

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EBS_APP_NAME: ${{ secrets.EBS_APP_NAME }}
      EBS_PREV_DOMAIN: pr${{ github.event.pull_request.number }}.edukona.com
      EBS_ENV_NAME: ${{secrets.EBS_ENV_BASE}}-${{ github.event.pull_request.number }}
      EBS_ENV_EXISTS: false
      EBS_ENV_CNAME_PREFIX: ${{secrets.ENV_CNAME_PREFIX}}${{ github.event.pull_request.number }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip install awscli==1.30.6
          pip install awsebcli --upgrade

          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-2

      - name: Remove the preview environments generated by the PR labels
        # loop through all labels on this PR and remove any preview environments
        run: |
          prNumber=${{ github.event.pull_request.number }}
          echo "Deleting Environment : pr$prNumber"
          DELETE_ENV_NAME=hice-frontend-${prNumber}

          # only terminate environment for label if that environment actually exists and is active (might not if label deploy failed)
          if aws elasticbeanstalk describe-environments --environment-names $DELETE_ENV_NAME --no-include-deleted | grep -q $DELETE_ENV_NAME; then
            echo "Terminating environment $DELETE_ENV_NAME"  
            eb terminate $DELETE_ENV_NAME --force
          else
            echo "Environment $DELETE_ENV_NAME does not exist. Skipping terminate."
          fi

      - name: Remove the Route53 DNS entries for deleted preview environments
        run: |
          prNumber=${{ github.event.pull_request.number }}
          echo "Deleting Route53 DNS entry if it exists."
          recordName="pr$prNumber.edukona.com"
          if aws route53 list-resource-record-sets --hosted-zone-id Z01753533QVX4IC2AQ784 --query "ResourceRecordSets[?Name == '$recordName.']" | grep -q $recordName; then
            aws route53 change-resource-record-sets --hosted-zone-id Z01753533QVX4IC2AQ784 \
            --change-batch '{
              "Changes": [
                {
                  "Action": "DELETE",
                  "ResourceRecordSet": {
                    "Name": "'${{ env.EBS_PREV_DOMAIN }}'",
                    "Type": "CNAME",
                    "TTL": 300,
                    "ResourceRecords": [
                      {
                        "Value": "'${{ env.EBS_ENV_CNAME_PREFIX }}'.us-west-2.elasticbeanstalk.com"
                      }
                    ]
                  }
                }
              ]
            }'
          else
            echo "Route53 DNS entry for $recordName does not exist, skipping deletion."
          fi
